version : '2.1'
services:
  mysql:
    image: mysql
    container_name: ssbd-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    expose:
      - "3306"
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  wildfly:
    build:
      context: ./wildfly
      dockerfile: Dockerfile
    container_name: ssbd-wildfly
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - "8080"
networks:
  default:
    driver: bridge